#!/usr/bin/env python
#
# Copyright (c) 2015 Catalyst.net Ltd
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

"""
Hamster to TKS in one command.

Michael Fincham <michael.fincham@catalyst.net.nz>
"""

import os
import argparse
import subprocess
import tempfile
import pty

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('-l', metavar="TIME", type=str, default='today', help='time specification for hamster2tks, defaults to today')
    parser.add_argument('-c', action='store_true', help='if specified, commits the changes to WRMS')
    args = parser.parse_args()

    tks_file = tempfile.NamedTemporaryFile(delete=False)
    tks_data = subprocess.check_output(['/usr/bin/hamster2tks' ,'--round=0.25', '-l', args.l])
    tks_file.write(tks_data)
    tks_file.close()

    pty.spawn(['/usr/bin/tks', tks_file.name, '-c' if args.c else ''])

    os.unlink(tks_file.name)
